#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        include_once $file;
        break;
    }
}

if($argv[1] === "csharp"){
    (new cvOutput\output($argv[2]))->csharp($argv[3]);
}elseif($argv[1] === "md"){
    (new cvOutput\output($argv[2]))->apiListMD($argv[3]);
}else{
    echo "type not find: $argv[1]\n";
}
